(function(){var h,aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},k="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function l(){l=function(){};k.Symbol||(k.Symbol=ba)}var ca=0;function ba(a){return"jscomp_symbol_"+(a||"")+ca++}
function n(){l();var a=k.Symbol.iterator;a||(a=k.Symbol.iterator=k.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(this)}});n=function(){}}function da(a){var b=0;return ea(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ea(a){n();a={next:a};a[k.Symbol.iterator]=function(){return this};return a}function fa(a){n();l();n();var b=a[Symbol.iterator];return b?b.call(a):da(a)}
function p(a){if(!(a instanceof Array)){a=fa(a);for(var b,c=[];!(b=a.next()).done;)c.push(b.value);a=c}return a}function ha(a,b){function c(){}c.prototype=b.prototype;a.Y=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}var q=window.Element.prototype,ia=q.matches||q.matchesSelector||q.webkitMatchesSelector||q.mozMatchesSelector||q.msMatchesSelector||q.oMatchesSelector;
function ja(a,b){if(a&&1==a.nodeType&&b){if("string"==typeof b||1==b.nodeType)return a==b||ka(a,b);if("length"in b)for(var c=0,d;d=b[c];c++)if(a==d||ka(a,d))return!0}return!1}function ka(a,b){if("string"!=typeof b)return!1;if(ia)return ia.call(a,b);b=a.parentNode.querySelectorAll(b);for(var c=0,d;d=b[c];c++)if(d==a)return!0;return!1}function la(a){for(var b=[];a&&a.parentNode&&1==a.parentNode.nodeType;)a=a.parentNode,b.push(a);return b}
function ma(a,b,c){function d(a){var d;if(g.composed&&"function"==typeof a.composedPath)for(var e=a.composedPath(),f=0,F;F=e[f];f++)1==F.nodeType&&ja(F,b)&&(d=F);else a:{if((d=a.target)&&1==d.nodeType&&b)for(d=[d].concat(la(d)),e=0;f=d[e];e++)if(ja(f,b)){d=f;break a}d=void 0}d&&c.call(d,a,d)}var e=document,g={composed:!0,I:!0},g=void 0===g?{}:g;e.addEventListener(a,d,g.I);return{l:function(){e.removeEventListener(a,d,g.I)}}}
function na(a){var b={};if(!a||1!=a.nodeType)return b;a=a.attributes;if(!a.length)return{};for(var c=0,d;d=a[c];c++)b[d.name]=d.value;return b}var oa=/:(80|443)$/,r=document.createElement("a"),t={};
function u(a){a=a&&"."!=a?a:location.href;if(t[a])return t[a];r.href=a;if("."==a.charAt(0)||"/"==a.charAt(0))return u(r.href);var b="80"==r.port||"443"==r.port?"":r.port,b="0"==b?"":b,c=r.host.replace(oa,"");return t[a]={hash:r.hash,host:c,hostname:r.hostname,href:r.href,origin:r.origin?r.origin:r.protocol+"//"+c,pathname:"/"==r.pathname.charAt(0)?r.pathname:"/"+r.pathname,port:b,protocol:r.protocol,search:r.search}}var v=[];
function pa(a,b){var c=this;this.context=a;this.G=b;this.f=(this.c=/Task$/.test(b))?a.get(b):a[b];this.b=[];this.a=[];this.g=function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];return c.a[c.a.length-1].apply(null,[].concat(p(b)))};this.c?a.set(b,this.g):a[b]=this.g}function w(a,b,c){a=qa(a,b);a.b.push(c);ra(a)}function x(a,b,c){a=qa(a,b);c=a.b.indexOf(c);-1<c&&(a.b.splice(c,1),0<a.b.length?ra(a):a.l())}
function ra(a){a.a=[];for(var b,c=0;b=a.b[c];c++){var d=a.a[c-1]||a.f.bind(a.context);a.a.push(b(d))}}pa.prototype.l=function(){var a=v.indexOf(this);-1<a&&(v.splice(a,1),this.c?this.context.set(this.G,this.f):this.context[this.G]=this.f)};function qa(a,b){var c=v.filter(function(c){return c.context==a&&c.G==b})[0];c||(c=new pa(a,b),v.push(c));return c}
function y(a,b,c,d,e,g){if("function"==typeof d){var f=c.get("buildHitTask");return{buildHitTask:function(c){c.set(a,null,!0);c.set(b,null,!0);d(c,e,g);f(c)}}}return z({},a,b)}function sa(a,b){var c=na(a),d={};Object.keys(c).forEach(function(a){if(!a.indexOf(b)&&a!=b+"on"){var e=c[a];"true"==e&&(e=!0);"false"==e&&(e=!1);a=ta(a.slice(b.length));d[a]=e}});return d}
function ua(a){"loading"==document.readyState?document.addEventListener("DOMContentLoaded",function c(){document.removeEventListener("DOMContentLoaded",c);a()}):a()}function va(a,b){var c;return function(d){for(var e=[],g=0;g<arguments.length;++g)e[g-0]=arguments[g];clearTimeout(c);c=setTimeout(function(){return a.apply(null,[].concat(p(e)))},b)}}function wa(a){function b(){c||(c=!0,a())}var c=!1;setTimeout(b,2E3);return b}var A={};
function xa(a,b){function c(){clearTimeout(e.timeout);e.send&&x(a,"send",e.send);delete A[d];e.H.forEach(function(a){return a()})}var d=a.get("trackingId"),e=A[d]=A[d]||{};clearTimeout(e.timeout);e.timeout=setTimeout(c,0);e.H=e.H||[];e.H.push(b);e.send||(e.send=function(a){return function(b){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];c();a.apply(null,[].concat(p(d)))}},w(a,"send",e.send))}
var z=Object.assign||function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(var d=0,e=c.length;d<e;d++){var g=Object(c[d]),f;for(f in g)Object.prototype.hasOwnProperty.call(g,f)&&(a[f]=g[f])}return a};function ta(a){return a.replace(/[\-\_]+(\w?)/g,function(a,c){return c.toUpperCase()})}function B(a){return"object"==typeof a&&null!==a}var C=function ya(b){return b?(b^16*Math.random()>>b/4).toString(16):"10000000-1000-4000-8000-100000000000".replace(/[018]/g,ya)};
function D(a,b){var c=window.GoogleAnalyticsObject||"ga";window[c]=window[c]||function(a){for(var b=[],d=0;d<arguments.length;++d)b[d-0]=arguments[d];(window[c].q=window[c].q||[]).push(b)};window.gaDevIds=window.gaDevIds||[];0>window.gaDevIds.indexOf("i5iSjo")&&window.gaDevIds.push("i5iSjo");window[c]("provide",a,b);window.gaplugins=window.gaplugins||{};window.gaplugins[a.charAt(0).toUpperCase()+a.slice(1)]=b}var E={J:1,U:2,K:3,M:4,V:5,N:6,O:7,W:8,X:9,L:10},G=Object.keys(E).length;
function H(a,b){a.set("\x26_av","2.4.1");var c=a.get("\x26_au"),c=parseInt(c||"0",16).toString(2);if(c.length<G)for(var d=G-c.length;d;)c="0"+c,d--;b=G-b;c=c.substr(0,b)+1+c.substr(b+1);a.set("\x26_au",parseInt(c||"0",2).toString(16))}function I(a,b){H(a,E.J);this.a=z({},b);this.g=a;this.b=this.a.stripQuery&&this.a.queryDimensionIndex?"dimension"+this.a.queryDimensionIndex:null;this.f=this.f.bind(this);this.c=this.c.bind(this);w(a,"get",this.f);w(a,"buildHitTask",this.c)}
I.prototype.f=function(a){var b=this;return function(c){if("page"==c||c==b.b){var d={location:a("location"),page:a("page")};return za(b,d)[c]}return a(c)}};I.prototype.c=function(a){var b=this;return function(c){var d=za(b,{location:c.get("location"),page:c.get("page")});c.set(d,null,!0);a(c)}};
function za(a,b){var c=u(b.page||b.location),d=c.pathname;if(a.a.indexFilename){var e=d.split("/");a.a.indexFilename==e[e.length-1]&&(e[e.length-1]="",d=e.join("/"))}"remove"==a.a.trailingSlash?d=d.replace(/\/+$/,""):"add"==a.a.trailingSlash&&(/\.\w+$/.test(d)||"/"==d.substr(-1)||(d+="/"));d={page:d+(a.a.stripQuery?Aa(a,c.search):c.search)};b.location&&(d.location=b.location);a.b&&(d[a.b]=c.search.slice(1)||"(not set)");return"function"==typeof a.a.urlFieldsFilter?(b=a.a.urlFieldsFilter(d,u),c={page:b.page,
location:b.location},a.b&&(c[a.b]=b[a.b]),c):d}function Aa(a,b){if(Array.isArray(a.a.queryParamsWhitelist)){var c=[];b.slice(1).split("\x26").forEach(function(b){var d=fa(b.split("\x3d"));b=d.next().value;d=d.next().value;-1<a.a.queryParamsWhitelist.indexOf(b)&&d&&c.push([b,d])});return c.length?"?"+c.map(function(a){return a.join("\x3d")}).join("\x26"):""}return""}I.prototype.remove=function(){x(this.g,"get",this.f);x(this.g,"buildHitTask",this.c)};D("cleanUrlTracker",I);
function Ba(a,b){var c=this;H(a,E.K);window.IntersectionObserver&&window.MutationObserver&&(this.a=z({rootMargin:"0px",fieldsObj:{},attributePrefix:"ga-"},b),this.c=a,this.C=this.C.bind(this),this.F=this.F.bind(this),this.A=this.A.bind(this),this.B=this.B.bind(this),this.b=null,this.items=[],this.i={},this.h={},ua(function(){c.a.elements&&c.observeElements(c.a.elements)}))}h=Ba.prototype;
h.observeElements=function(a){var b=this;a=J(this,a);this.items=this.items.concat(a.items);this.i=z({},a.i,this.i);this.h=z({},a.h,this.h);a.items.forEach(function(a){var c=b.h[a.threshold]=b.h[a.threshold]||new IntersectionObserver(b.F,{rootMargin:b.a.rootMargin,threshold:[+a.threshold]});(a=b.i[a.id]||(b.i[a.id]=document.getElementById(a.id)))&&c.observe(a)});this.b||(this.b=new MutationObserver(this.C),this.b.observe(document.body,{childList:!0,subtree:!0}));requestAnimationFrame(function(){})};
h.unobserveElements=function(a){var b=[],c=[];this.items.forEach(function(d){a.some(function(a){a=Ca(a);return a.id===d.id&&a.threshold===d.threshold&&a.trackFirstImpressionOnly===d.trackFirstImpressionOnly})?c.push(d):b.push(d)});if(b.length){var d=J(this,b),e=J(this,c);this.items=d.items;this.i=d.i;this.h=d.h;c.forEach(function(a){if(!d.i[a.id]){var b=e.h[a.threshold],c=e.i[a.id];c&&b.unobserve(c);d.h[a.threshold]||e.h[a.threshold].disconnect()}})}else this.unobserveAllElements()};
h.unobserveAllElements=function(){var a=this;Object.keys(this.h).forEach(function(b){a.h[b].disconnect()});this.b.disconnect();this.b=null;this.items=[];this.i={};this.h={}};function J(a,b){var c=[],d={},e={};b.length&&b.forEach(function(b){b=Ca(b);c.push(b);e[b.id]=a.i[b.id]||null;d[b.threshold]=a.h[b.threshold]||null});return{items:c,i:e,h:d}}h.C=function(a){for(var b=0,c;c=a[b];b++){for(var d=0,e;e=c.removedNodes[d];d++)K(this,e,this.B);for(d=0;e=c.addedNodes[d];d++)K(this,e,this.A)}};
function K(a,b,c){1==b.nodeType&&b.id in a.i&&c(b.id);for(var d=0,e;e=b.childNodes[d];d++)K(a,e,c)}
h.F=function(a){for(var b=[],c=0,d;d=a[c];c++)for(var e=0,g;g=this.items[e];e++){var f;if(f=d.target.id===g.id)(f=g.threshold)?f=d.intersectionRatio>=f:(f=d.intersectionRect,f=0<f.top||0<f.bottom||0<f.left||0<f.right);if(f){var m=g.id;f=document.getElementById(m);var m={transport:"beacon",eventCategory:"Viewport",eventAction:"impression",eventLabel:m,nonInteraction:!0},Ha=z({},this.a.fieldsObj,sa(f,this.a.attributePrefix));this.c.send("event",y(m,Ha,this.c,this.a.hitFilter,f));g.trackFirstImpressionOnly&&
b.push(g)}}b.length&&this.unobserveElements(b)};h.A=function(a){var b=this,c=this.i[a]=document.getElementById(a);this.items.forEach(function(d){a==d.id&&b.h[d.threshold].observe(c)})};h.B=function(a){var b=this,c=this.i[a];this.items.forEach(function(d){a==d.id&&b.h[d.threshold].unobserve(c)});this.i[a]=null};h.remove=function(){this.unobserveAllElements()};D("impressionTracker",Ba);function Ca(a){"string"==typeof a&&(a={id:a});return z({threshold:0,trackFirstImpressionOnly:!0},a)}
function Da(){this.a={}}function Ea(a,b){(a.a.externalSet=a.a.externalSet||[]).push(b)}Da.prototype.P=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];(this.a[a]=this.a[a]||[]).forEach(function(a){return a.apply(null,[].concat(p(c)))})};var L={},M=!1,N;function O(a,b){b=void 0===b?{}:b;this.a={};this.b=a;this.v=b;this.j=null}ha(O,Da);function P(a,b,c){a=["autotrack",a,b].join(":");L[a]||(L[a]=new O(a,c),M||(window.addEventListener("storage",Fa),M=!0));return L[a]}
function Q(){if(null!=N)return N;try{window.localStorage.setItem("autotrack","autotrack"),window.localStorage.removeItem("autotrack"),N=!0}catch(a){N=!1}return N}O.prototype.get=function(){if(this.j)return this.j;if(Q())try{this.j=R(window.localStorage.getItem(this.b))}catch(a){}return this.j=z({},this.v,this.j)};O.prototype.set=function(a){this.j=z({},this.v,this.j,a);if(Q())try{var b=JSON.stringify(this.j);window.localStorage.setItem(this.b,b)}catch(c){}};
function S(a){a.j={};if(Q())try{window.localStorage.removeItem(a.b)}catch(b){}}O.prototype.l=function(){delete L[this.b];Object.keys(L).length||(window.removeEventListener("storage",Fa),M=!1)};function Fa(a){var b=L[a.key];if(b){var c=z({},b.v,R(a.oldValue));a=z({},b.v,R(a.newValue));b.j=a;b.P("externalSet",a,c)}}function R(a){var b={};if(a)try{b=JSON.parse(a)}catch(c){}return b}var T={};
function U(a,b,c){this.f=a;this.timeout=b||V;this.timeZone=c;this.b=this.b.bind(this);w(a,"sendHitTask",this.b);try{this.c=new Intl.DateTimeFormat("en-US",{timeZone:this.timeZone})}catch(d){}this.a=P(a.get("trackingId"),"session",{hitTime:0,isExpired:!1});this.a.get().id||this.a.set({id:C()})}function Ga(a,b,c){var d=a.get("trackingId");return T[d]?T[d]:T[d]=new U(a,b,c)}function W(a){return a.a.get().id}
U.prototype.isExpired=function(a){a=void 0===a?W(this):a;if(a!=W(this))return!0;a=this.a.get();if(a.isExpired)return!0;var b=a.hitTime;return b&&(a=new Date,b=new Date(b),a-b>6E4*this.timeout||this.c&&this.c.format(a)!=this.c.format(b))?!0:!1};U.prototype.b=function(a){var b=this;return function(c){a(c);var d=c.get("sessionControl");c="start"==d||b.isExpired();var d="end"==d,e=b.a.get();e.hitTime=+new Date;c&&(e.isExpired=!1,e.id=C());d&&(e.isExpired=!0);b.a.set(e)}};
U.prototype.l=function(){x(this.f,"sendHitTask",this.b);this.a.l();delete T[this.f.get("trackingId")]};var V=30;function X(a,b){H(a,E.L);window.addEventListener&&(this.b=z({increaseThreshold:20,sessionTimeout:V,fieldsObj:{}},b),this.f=a,this.c=Ia(this),this.g=va(this.g.bind(this),500),this.o=this.o.bind(this),this.a=P(a.get("trackingId"),"plugins/max-scroll-tracker"),this.m=Ga(a,this.b.sessionTimeout,this.b.timeZone),w(a,"set",this.o),Ja(this))}
function Ja(a){100>(a.a.get()[a.c]||0)&&window.addEventListener("scroll",a.g)}
X.prototype.g=function(){var a=document.documentElement,b=document.body,a=Math.min(100,Math.max(0,Math.round(window.pageYOffset/(Math.max(a.offsetHeight,a.scrollHeight,b.offsetHeight,b.scrollHeight)-window.innerHeight)*100))),b=W(this.m);b!=this.a.get().sessionId&&(S(this.a),this.a.set({sessionId:b}));if(this.m.isExpired(this.a.get().sessionId))S(this.a);else if(b=this.a.get()[this.c]||0,a>b&&(100!=a&&100!=b||window.removeEventListener("scroll",this.g),b=a-b,100==a||b>=this.b.increaseThreshold)){var c=
{};this.a.set((c[this.c]=a,c.sessionId=W(this.m),c));a={transport:"beacon",eventCategory:"Max Scroll",eventAction:"increase",eventValue:b,eventLabel:String(a),nonInteraction:!0};this.b.maxScrollMetricIndex&&(a["metric"+this.b.maxScrollMetricIndex]=b);this.f.send("event",y(a,this.b.fieldsObj,this.f,this.b.hitFilter))}};X.prototype.o=function(a){var b=this;return function(c,d){a(c,d);var e={};(B(c)?c:(e[c]=d,e)).page&&(c=b.c,b.c=Ia(b),b.c!=c&&Ja(b))}};
function Ia(a){a=u(a.f.get("page")||a.f.get("location"));return a.pathname+a.search}X.prototype.remove=function(){this.m.l();window.removeEventListener("scroll",this.g);x(this.f,"set",this.o)};D("maxScrollTracker",X);var Ka={};function La(a,b){H(a,E.M);window.matchMedia&&(this.a=z({changeTemplate:this.changeTemplate,changeTimeout:1E3,fieldsObj:{}},b),B(this.a.definitions)&&(b=this.a.definitions,this.a.definitions=Array.isArray(b)?b:[b],this.b=a,this.c=[],Ma(this)))}
function Ma(a){a.a.definitions.forEach(function(b){if(b.name&&b.dimensionIndex){var c=Na(b);a.b.set("dimension"+b.dimensionIndex,c);Oa(a,b)}})}function Na(a){var b;a.items.forEach(function(a){Pa(a.media).matches&&(b=a)});return b?b.name:"(not set)"}
function Oa(a,b){b.items.forEach(function(c){c=Pa(c.media);var d=va(function(){var c=Na(b),d=a.b.get("dimension"+b.dimensionIndex);c!==d&&(a.b.set("dimension"+b.dimensionIndex,c),c={transport:"beacon",eventCategory:b.name,eventAction:"change",eventLabel:a.a.changeTemplate(d,c),nonInteraction:!0},a.b.send("event",y(c,a.a.fieldsObj,a.b,a.a.hitFilter)))},a.a.changeTimeout);c.addListener(d);a.c.push({T:c,R:d})})}La.prototype.remove=function(){for(var a=0,b;b=this.c[a];a++)b.T.removeListener(b.R)};
La.prototype.changeTemplate=function(a,b){return a+" \x3d\x3e "+b};D("mediaQueryTracker",La);function Pa(a){return Ka[a]||(Ka[a]=window.matchMedia(a))}function Y(a,b){var c=this;H(a,E.N);window.addEventListener&&(this.a=z({events:["click"],linkSelector:"a, area",shouldTrackOutboundLink:this.shouldTrackOutboundLink,fieldsObj:{},attributePrefix:"ga-"},b),this.b=a,this.f=this.f.bind(this),this.c={},this.a.events.forEach(function(a){c.c[a]=ma(a,c.a.linkSelector,c.f)}))}
Y.prototype.f=function(a,b){var c=this;if(this.a.shouldTrackOutboundLink(b,u)){var d=b.getAttribute("href")||b.getAttribute("xlink:href"),e=u(d),e={transport:"beacon",eventCategory:"Outbound Link",eventAction:a.type,eventLabel:e.href},g=z({},this.a.fieldsObj,sa(b,this.a.attributePrefix)),f=y(e,g,this.b,this.a.hitFilter,b,a);if(navigator.sendBeacon||"click"!=a.type||"_blank"==b.target||a.metaKey||a.ctrlKey||a.shiftKey||a.altKey||1<a.which)this.b.send("event",f);else{var m=function(){window.removeEventListener("click",
m);if(!a.defaultPrevented){a.preventDefault();var b=f.hitCallback;f.hitCallback=wa(function(){"function"==typeof b&&b();location.href=d})}c.b.send("event",f)};window.addEventListener("click",m)}}};Y.prototype.shouldTrackOutboundLink=function(a,b){a=a.getAttribute("href")||a.getAttribute("xlink:href");b=b(a);return b.hostname!=location.hostname&&"http"==b.protocol.slice(0,4)};Y.prototype.remove=function(){var a=this;Object.keys(this.c).forEach(function(b){a.c[b].l()})};D("outboundLinkTracker",Y);
var Z=C();
function Qa(a,b){var c=this;H(a,E.O);document.visibilityState&&(this.a=z({sessionTimeout:V,visibleThreshold:5E3,sendInitialPageview:!1,fieldsObj:{}},b),this.b=a,this.g=document.visibilityState,this.m=null,this.o=!1,this.u=this.u.bind(this),this.s=this.s.bind(this),this.w=this.w.bind(this),this.D=this.D.bind(this),this.c=P(a.get("trackingId"),"plugins/page-visibility-tracker"),Ea(this.c,this.D),this.f=Ga(a,this.a.sessionTimeout,this.a.timeZone),w(a,"set",this.u),window.addEventListener("unload",this.w),
document.addEventListener("visibilitychange",this.s),xa(this.b,function(){if("visible"==document.visibilityState)c.a.sendInitialPageview&&(Ra(c,{S:!0}),c.o=!0),c.c.set({time:+new Date,state:"visible",pageId:Z,sessionId:W(c.f)});else if(c.a.sendInitialPageview&&c.a.pageLoadsMetricIndex){var a={},a=(a.transport="beacon",a.eventCategory="Page Visibility",a.eventAction="page load",a.eventLabel="(not set)",a["metric"+c.a.pageLoadsMetricIndex]=1,a.nonInteraction=!0,a);c.b.send("event",y(a,c.a.fieldsObj,
c.b,c.a.hitFilter))}}))}h=Qa.prototype;
h.s=function(){var a=this;if("visible"==document.visibilityState||"hidden"==document.visibilityState){var b=Sa(this),c={time:+new Date,state:document.visibilityState,pageId:Z,sessionId:W(this.f)};"visible"==document.visibilityState&&this.a.sendInitialPageview&&!this.o&&(Ra(this),this.o=!0);"hidden"==document.visibilityState&&this.m&&clearTimeout(this.m);this.f.isExpired(b.sessionId)?(S(this.c),"hidden"==this.g&&"visible"==document.visibilityState&&(clearTimeout(this.m),this.m=setTimeout(function(){a.c.set(c);
Ra(a,{hitTime:c.time})},this.a.visibleThreshold))):(b.pageId==Z&&"visible"==b.state&&Ta(this,b),this.c.set(c));this.g=document.visibilityState}};function Sa(a){var b=a.c.get();"visible"==a.g&&"hidden"==b.state&&b.pageId!=Z&&(b.state="visible",b.pageId=Z,a.c.set(b));return b}
function Ta(a,b,c){c=(c?c:{}).hitTime;var d={hitTime:c},d=(d?d:{}).hitTime;(b=b.time?(d||+new Date)-b.time:0)&&b>=a.a.visibleThreshold&&(b=Math.round(b/1E3),d={transport:"beacon",nonInteraction:!0,eventCategory:"Page Visibility",eventAction:"track",eventValue:b,eventLabel:"(not set)"},c&&(d.queueTime=+new Date-c),a.a.visibleMetricIndex&&(d["metric"+a.a.visibleMetricIndex]=b),a.b.send("event",y(d,a.a.fieldsObj,a.b,a.a.hitFilter)))}
function Ra(a,b){var c=b?b:{};b=c.hitTime;var c=c.S,d={transport:"beacon"};b&&(d.queueTime=+new Date-b);c&&a.a.pageLoadsMetricIndex&&(d["metric"+a.a.pageLoadsMetricIndex]=1);a.b.send("pageview",y(d,a.a.fieldsObj,a.b,a.a.hitFilter))}h.u=function(a){var b=this;return function(c,d){var e={},e=B(c)?c:(e[c]=d,e);e.page&&e.page!==b.b.get("page")&&"visible"==b.g&&b.s();a(c,d)}};h.D=function(a,b){a.time!=b.time&&(b.pageId!=Z||"visible"!=b.state||this.f.isExpired(b.sessionId)||Ta(this,b,{hitTime:a.time}))};
h.w=function(){"hidden"!=this.g&&this.s()};h.remove=function(){this.c.l();this.f.l();x(this.b,"set",this.u);window.removeEventListener("unload",this.w);document.removeEventListener("visibilitychange",this.s)};D("pageVisibilityTracker",Qa);})();
//# sourceMappingURL=autotrack.filmaj.js.map