markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:year/:title/
defaults:
  -
    scope:
      path: "presentations"
      type: "pages" # previously `page` in Jekyll 2.2.
    values:
      layout: "presentation" # overrides previous default layout
